export const allTables = [
  {
    id: 4,
    capacity: 5,
    x: 1,
    y: 2,
    tableNumber: 4,
    restaurant: null,
    reservations: [],
  },
  {
    id: 2,
    capacity: 2,
    x: 0,
    y: 0,
    tableNumber: 2,
    restaurant: null,
    reservations: [],
  },
  {
    id: 1,
    capacity: 4,
    x: 1,
    y: 1,
    tableNumber: 1,
    restaurant: null,
    reservations: [],
  },
  {
    id: 3,
    capacity: 6,
    x: 2,
    y: 3,
    tableNumber: 3,
    restaurant: null,
    reservations: [],
  },
  {
    id: 5,
    capacity: 3,
    x: 3,
    y: 2,
    tableNumber: 5,
    restaurant: null,
    reservations: [],
  },
];

export const reservedTables = [
    {
        id: 2,
        capacity: 2,
        x: 0,
        y: 0,
        tableNumber: 2,
        restaurant: null,
        reservations: [],
      },
      {
        id: 1,
        capacity: 4,
        x: 1,
        y: 1,
        tableNumber: 1,
        restaurant: null,
        reservations: [],
      },
]